# Generated by Django 6.1 on 2026-09-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
